//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANITORIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccoutn
    {
        public int id { get; set; }
        public string bankName { get; set; }
        public string account { get; set; }
        public int v_id { get; set; }
        public string bankGudi { get; set; }
    }
}
