//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANITORIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int id { get; set; }
        public string Recid { get; set; }
        public string po_id { get; set; }
        public string product { get; set; }
        public string varientID { get; set; }
        public string varient { get; set; }
        public string qty { get; set; }
        public string REC_qty { get; set; }
        public string unitprice { get; set; }
        public string taxes { get; set; }
        public string subtotal { get; set; }
        public string pid { get; set; }
        public string P_name { get; set; }
        public string p_des { get; set; }
        public string p_type { get; set; }
        public string p_tax { get; set; }
        public string invoicingPolicy { get; set; }
        public string salesPrice { get; set; }
        public string cost { get; set; }
        public string total { get; set; }
        public string subCategory { get; set; }
        public string unit { get; set; }
        public string category { get; set; }
        public string brand { get; set; }
        public string company { get; set; }
    }
}
