//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANITORIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTs_of_Requisition
    {
        public int id { get; set; }
        public Nullable<int> Requisitionid { get; set; }
        public Nullable<int> Recievedid { get; set; }
        public Nullable<int> Recieved_product_id { get; set; }
        public string productName { get; set; }
        public string varient { get; set; }
        public string status { get; set; }
        public Nullable<int> qty { get; set; }
    }
}
