//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANITORIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public int id { get; set; }
        public string VariantName { get; set; }
        public string values { get; set; }
        public Nullable<bool> isMultiList { get; set; }
    }
}
