//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANITORIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsVariant_
    {
        public int id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> variantID { get; set; }
        public string variantValues { get; set; }
        public string variantGuid { get; set; }
    }
}
