//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANITORIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBill
    {
        public int ID { get; set; }
        public string bill_id { get; set; }
        public string SQ { get; set; }
        public string SO { get; set; }
        public string SALES_rec { get; set; }
        public string payMethod { get; set; }
        public Nullable<long> totalAmount { get; set; }
        public Nullable<System.DateTime> createat { get; set; }
        public Nullable<System.DateTime> updateat { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<int> updatedBy { get; set; }
    }
}
