//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANITORIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int id { get; set; }
        public string email { get; set; }
        public string CompleteName { get; set; }
        public string password { get; set; }
        public string contactNo { get; set; }
        public string nic { get; set; }
        public string imgGuid { get; set; }
        public Nullable<int> policyid { get; set; }
        public Nullable<System.DateTime> createAT { get; set; }
        public Nullable<System.DateTime> updateAT { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
