//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANITORIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public int id { get; set; }
        public string vendorName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string zipcode { get; set; }
        public string address { get; set; }
    }
}
